### ISSUE TITLE
Great Layout - Questions

### ISSUE THREAD

**Issue by monbro** [plumvillage/plumvillage#1]
Hello,
do you have any information about the licence you released it? (MIT?)
I tried to download the theme folder, uploaded and activate it (with latest empty wordpress install), unfortunately the page was empty. Is there any page required to create?

Thank you very much,
Michael

**Comment by maartenhunink** [comment]
Hey Michael,

Happy you like the layout. 

Sorry you were disappointed to find that installing the theme didn't give you the expected results. The main issue is that this repository has been mostly used by us to deploy the theme to the site, and while developing the theme we haven't taken into account that it would be used and installed by others. So getting the same layout as on our site, requires setting up pages, blocks, custom fields, etc... which currently doesn't happen when you install the theme. And I am not sure we have the resources at the moment to make that happen.

I should probably explain this in the readme, or just make it a private repository...

Sorry for the confusion.

Maarten

**Comment by monbro** [comment]
Hi Maarten, thank you very much for the explanation. No worries, I understand, its okay! I managed to get the basic theme working by simply installing the wordpress plugin advanced custom fields. Have a beautiful day!
